# Hamilton matrices for spin models

Quantum states are represented by binary number which can be converted to a decimal number.

We start with state n, and by applying the algorithm provided in the lecture this state is modified by the operator $J_{i,j}^{\alpha}S_i^{\alpha}S_j^{\alpha}$.

We now want to construct a matrix using this algorithm.

In [6]:
using LinearAlgebra, SparseArrays, DelimitedFiles
#Specifying the number of particles and the interaction matrices 
N=3
jmat = zeros(Int8, N, N, 3);

In [7]:
function MakeHam(jmat)
    ham = spzeros(Float64,2^N, 2^N) #create empty sparse
    for n in 0:2^N-1 #going trhough all possible states n
        nbin=digits(n, base = 2, pad = N) #finding the binary corresponding to n (the state)
        for i in 1:N #i,j going through the elements of the J-matrices
            for j in i+1:N
                zi=nbin[i] #the ith number of the binary number (0 or 1) 
                zj=nbin[j]
                l = n +(1-2zi)*2^(i-1)+(1-2zj)*2^(j-1)
                ham[l+1,n+1] += -(1/4)*jmat[i,j,1] #x-link
                ham[l+1,n+1] += (1/4)*jmat[i,j,2]*(2zi-1)*(2zj-1) #y-link
                ham[n+1,n+1] += -jmat[i,j,3]*(2zi-1)*(2zj-1) #z-link
            end
        end
    end
    return ham
end

MakeHam (generic function with 1 method)

Now define J matrices and find the corresponding hamiltonian.

In [8]:
N=4
jmat = zeros(Int8, N, N, 3);

#Ising model
#jmat[1,2,3]=jmat[1,3,3]=jmat[2,3,3]=jmat[2,1,3]=jmat[3,1,3]=jmat[3,2,3]=-1
#jmat[1,2,3]=jmat[2,3,3]=jmat[2,1,3]=jmat[3,2,3]=-1
for i in 1:N-1
    jmat[i,i+1,3]=jmat[i+1,i,3]=1
end
mat1=Matrix(MakeHam(jmat))
mat1


N=4

#Heisenberg
jmat = zeros(Int8, N, N, 3);
for i in 1:N-1
    for a in 1:3
        jmat[i,i+1,a]=jmat[i+1,i,a]=-1
    end
end

mat2=Matrix(MakeHam(jmat));

#=
#Specified model
jmat = zeros(Int8, N, N, 3)
jmat[1,2,1]=jmat[2,3,2]=jmat[1,3,3]=1
mat3=Matrix(MakeHam(jmat))
display(mat3)=#

## Ising model, eigensystem

In [6]:
display(eigvals(mat1))
eigvecs(mat1)

256-element Array{Float64,1}:
 -7.0
 -7.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
  ⋮  
  5.0
  5.0
  5.0
  5.0
  5.0
  5.0
  5.0
  5.0
  5.0
  5.0
  7.0
  7.0

256×256 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.

## Heisenberg

In [9]:
display(eigvals(mat2))
heiseigvec=eigvecs(mat2)

16-element Array{Float64,1}:
 -3.462171996010125 
 -3.0615528128088307
 -1.596291201783627 
 -1.596291201783626 
 -0.9999999999999992
 -0.6513878188659976
 -0.6513878188659973
 -0.6075329837426913
  1.0615528128088296
  1.0697049797528164
  1.096291201783626 
  1.0962912017836264
  1.1513878188659974
  1.151387818865998 
  3.0               
  3.0               

16×16 Array{Float64,2}:
  0.0           0.0           0.0       …  0.0        0.0          1.0  0.0
 -6.90275e-19   0.0           0.0          0.0        0.676766     0.0  0.0
  6.16025e-18   0.0           0.0          0.0        0.204908     0.0  0.0
 -0.0730174     0.0863966     0.0          0.0        4.57967e-16  0.0  0.0
 -2.96449e-17   2.2933e-17    0.0          0.0        0.204908     0.0  0.0
  0.651632     -0.701809      0.0       …  0.0        1.66533e-16  0.0  0.0
 -0.264658     -1.17961e-16   0.0          0.0        1.32039e-16  0.0  0.0
  0.0           0.0           0.133719     0.676766   0.0          0.0  0.0
  1.11022e-16  -5.55112e-17   0.0          0.0        0.676766     0.0  0.0
 -0.264658     -1.11022e-16   0.0          0.0       -1.57669e-16  0.0  0.0
  0.651632      0.701809      0.0       …  0.0       -9.75005e-17  0.0  0.0
  0.0           0.0          -0.694348     0.204908   0.0          0.0  0.0
 -0.0730174    -0.0863966     0.0          0.0       -7.83895e-1

In [12]:
mat2

16×16 Array{Float64,2}:
 3.0  0.0   0.0  0.0   0.0   0.0   0.0  …   0.0   0.0  0.0   0.0  0.0  0.0
 0.0  1.0   0.5  0.0   0.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.5  -1.0  0.0   0.5   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  1.0   0.0   0.5   0.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.5  0.0  -1.0   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.5   0.0  -3.0   0.5  …   0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.5  -1.0      0.5   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.0   0.0      0.0   0.5  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.5   0.0   0.0      0.0   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.5   0.0      0.5   0.0  0.0   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.0   0.5  …  -3.0   0.0  0.5   0.0  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.0   0.0      0.0  -1.0  0.0   0.5  0.0  0.0
 0.0  0.0   0.0  0.0   0.0   0.0   0.0      0.5   0.0  1.0   0.0  0.0  0.0
 

In [8]:
writedlm("heisgs.txt",heiseigvec[:,1])

## Specified model

In [13]:
display(eigvals(mat3))
eigvecs(mat3)

8-element Array{Float64,1}:
 -0.4330127018922194 
 -0.4330127018922194 
 -0.43301270189221935
 -0.43301270189221924
  0.43301270189221913
  0.43301270189221924
  0.4330127018922193 
  0.4330127018922194 

8×8 Array{Float64,2}:
 -0.627963      0.157402     -0.607916     …   0.137013      0.0     
 -1.11022e-16  -0.314681     -0.0814772       -0.569453     -0.627963
  0.0          -0.859723     -0.2226           0.416869      0.0     
  0.0           0.115226     -0.445026        -0.374328      0.0     
  5.55112e-17  -0.314681     -0.0814772       -0.569453      0.627963
  0.627963      0.157402     -0.607916     …   0.137013      0.0     
  0.459701      2.77556e-17  -7.63278e-17      5.55112e-17   0.0     
  0.0           0.0           0.0              0.0          -0.459701