# Hamilton matrices for spin models

Quantum states are represented by binary number which can be converted to a decimal number.

We start with state n, and by applying the algorithm provided in the lecture this state is modified by the operator $J_{i,j}^{\alpha}S_i^{\alpha}S_j^{\alpha}$.

We now want to construct a matrix using this algorithm.

In [8]:
using LinearAlgebra, SparseArrays
#Specifying the number of particles and the interaction matrices 
N=3
jmat = zeros(Int8, N, N, 3);

In [9]:
function MakeHam(jmat)
    ham = spzeros(Float64,2^N, 2^N) #create empty sparse
    for n in 0:2^N-1 #going trhough all possible states n
        nbin=digits(n, base = 2, pad = N) #finding the binary corresponding to n (the state)
        for i in 1:N #i,j going through the elements of the J-matrices
            for j in i+1:N
                zi=nbin[i] #the ith number of the binary number (0 or 1) 
                zj=nbin[j]
                l = n +(1-2zi)*2^(i-1)+(1-2zj)*2^(j-1)
                ham[l+1,n+1] += -(1/4)*jmat[i,j,1] #x-link
                ham[l+1,n+1] += (1/4)*jmat[i,j,2]*(2zi-1)*(2zj-1) #y-link
                ham[n+1,n+1] += -(1/4)*jmat[i,j,3]*(2zi-1)*(2zj-1) #z-link
            end
        end
    end
    return ham
end

MakeHam (generic function with 1 method)

Now define J matrices and find the corresponding hamiltonian.

In [10]:
#Ising model
jmat[1,2,3]=jmat[1,3,3]=jmat[2,3,3]=jmat[2,1,3]=jmat[3,1,3]=jmat[3,2,3]=1
mat1=Matrix(MakeHam(jmat))
display(mat1)

#Isotropic model
for i in 1:N
    for j in 1:N
        for a in 1:3
            if i != j
                jmat[i,j,a]=1
            end
        end
    end
end
mat2=Matrix(MakeHam(jmat))
display(mat2)

#Specified model
jmat = zeros(Int8, N, N, 3)
jmat[1,2,1]=jmat[2,3,2]=jmat[1,3,3]=1
mat3=Matrix(MakeHam(jmat))
display(mat3)

8×8 Array{Float64,2}:
 -0.75  0.0   0.0   0.0   0.0   0.0   0.0    0.0 
  0.0   0.25  0.0   0.0   0.0   0.0   0.0    0.0 
  0.0   0.0   0.25  0.0   0.0   0.0   0.0    0.0 
  0.0   0.0   0.0   0.25  0.0   0.0   0.0    0.0 
  0.0   0.0   0.0   0.0   0.25  0.0   0.0    0.0 
  0.0   0.0   0.0   0.0   0.0   0.25  0.0    0.0 
  0.0   0.0   0.0   0.0   0.0   0.0   0.25   0.0 
  0.0   0.0   0.0   0.0   0.0   0.0   0.0   -0.75

8×8 Array{Float64,2}:
 -0.75   0.0    0.0    0.0    0.0    0.0    0.0    0.0 
  0.0    0.25  -0.5    0.0   -0.5    0.0    0.0    0.0 
  0.0   -0.5    0.25   0.0   -0.5    0.0    0.0    0.0 
  0.0    0.0    0.0    0.25   0.0   -0.5   -0.5    0.0 
  0.0   -0.5   -0.5    0.0    0.25   0.0    0.0    0.0 
  0.0    0.0    0.0   -0.5    0.0    0.25  -0.5    0.0 
  0.0    0.0    0.0   -0.5    0.0   -0.5    0.25   0.0 
  0.0    0.0    0.0    0.0    0.0    0.0    0.0   -0.75

8×8 Array{Float64,2}:
 -0.25   0.0    0.0   -0.25   0.0    0.0    0.25   0.0 
  0.0    0.25  -0.25   0.0    0.0    0.0    0.0    0.25
  0.0   -0.25  -0.25   0.0   -0.25   0.0    0.0    0.0 
 -0.25   0.0    0.0    0.25   0.0   -0.25   0.0    0.0 
  0.0    0.0   -0.25   0.0    0.25   0.0    0.0   -0.25
  0.0    0.0    0.0   -0.25   0.0   -0.25  -0.25   0.0 
  0.25   0.0    0.0    0.0    0.0   -0.25   0.25   0.0 
  0.0    0.25   0.0    0.0   -0.25   0.0    0.0   -0.25

## Ising model, eigensystem

In [11]:
display(eigvals(mat1))
eigvecs(mat1)

8-element Array{Float64,1}:
 -0.75
 -0.75
  0.25
  0.25
  0.25
  0.25
  0.25
  0.25

8×8 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

## Heisenberg

In [12]:
display(eigvals(mat2))
eigvecs(mat2)

8-element Array{Float64,1}:
 -0.75              
 -0.75              
 -0.75              
 -0.75              
  0.75              
  0.75              
  0.7500000000000002
  0.7500000000000002

8×8 Array{Float64,2}:
 1.0  0.0   0.0       0.0       0.0        0.0        0.0        0.0     
 0.0  0.0  -0.57735   0.0       0.0        0.707107   0.0       -0.408248
 0.0  0.0  -0.57735   0.0       0.0       -0.707107   0.0       -0.408248
 0.0  0.0   0.0      -0.57735   0.707107   0.0       -0.408248   0.0     
 0.0  0.0  -0.57735   0.0       0.0        0.0        0.0        0.816497
 0.0  0.0   0.0      -0.57735  -0.707107   0.0       -0.408248   0.0     
 0.0  0.0   0.0      -0.57735   0.0        0.0        0.816497   0.0     
 0.0  1.0   0.0       0.0       0.0        0.0        0.0        0.0     

## Specified model

In [13]:
display(eigvals(mat3))
eigvecs(mat3)

8-element Array{Float64,1}:
 -0.4330127018922194 
 -0.4330127018922194 
 -0.43301270189221935
 -0.43301270189221924
  0.43301270189221913
  0.43301270189221924
  0.4330127018922193 
  0.4330127018922194 

8×8 Array{Float64,2}:
 -0.627963      0.157402     -0.607916     …   0.137013      0.0     
 -1.11022e-16  -0.314681     -0.0814772       -0.569453     -0.627963
  0.0          -0.859723     -0.2226           0.416869      0.0     
  0.0           0.115226     -0.445026        -0.374328      0.0     
  5.55112e-17  -0.314681     -0.0814772       -0.569453      0.627963
  0.627963      0.157402     -0.607916     …   0.137013      0.0     
  0.459701      2.77556e-17  -7.63278e-17      5.55112e-17   0.0     
  0.0           0.0           0.0              0.0          -0.459701