# Hamilton matrices for 2D spin models

We can re-use the Hamiltonian-construction algorithm for the 2D case. By labeling the sites as:  
 $$1\,\,2\,\,\,3\,\,\,\,4\,\,\,\,5\,\,\,\,6\\
   7\,\,8\,\,9\,\,10\,11\,12$$
and adding the right interaction terms in the J-matrices, a multi dimensional model can be emulated.

In [ ]:
#import Pkg; Pkg.add("Arpack")

In [1]:
using LinearAlgebra, SparseArrays, DelimitedFiles, Arpack, Plots

#Including the functions to construct a Hamiltonian and calculate the entanglement entropy
include("functions.jl") #MakeHam, RedDens, EntEntr, PopMul, BinDec

Now define J matrices and find the corresponding hamiltonian.

In [2]:

#################
#Ising model
#################
N=10
J=-1
jmat = zeros(Int8, N, N, 3);

for i in 1:Int(N/2-1)
    jmat[i,i+1,3]=jmat[i+1,i,3]=J
end
for i in Int(N/2+1):(N-1)
    jmat[i,i+1,3]=jmat[i+1,i,3]=J
end
for i in 1:Int(N/2)
    jmat[i,i+Int(N/2),3]=jmat[i+Int(N/2),i,3]=J
end

mat1=MakeHam(jmat)
matrix1=Matrix(mat1)

##################
#Heisenberg
##################
#=
N=12
J=1
jmat = zeros(Int8, N, N, 3);
for a in 1:3
    for i in 1:Int(N/2-1)
        jmat[i,i+1,a]=jmat[i+1,i,a]=J
    end
    for i in Int(N/2+1):(N-1)
        jmat[i,i+1,a]=jmat[i+1,i,a]=J
    end
    for i in 1:Int(N/2)
        jmat[i,i+6,a]=jmat[i+6,i,a]=J
    end
end


mat2=MakeHam(jmat);
=#

1024×1024 Array{Float64,2}:
 -13.0   0.0   0.0   0.0   0.0   0.0  …   0.0   0.0   0.0   0.0   0.0    0.0
   0.0  -9.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0    0.0
   0.0   0.0  -7.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0    0.0
   0.0   0.0   0.0  -7.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0    0.0
   0.0   0.0   0.0   0.0  -7.0   0.0      0.0   0.0   0.0   0.0   0.0    0.0
   0.0   0.0   0.0   0.0   0.0  -3.0  …   0.0   0.0   0.0   0.0   0.0    0.0
   0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0    0.0
   0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0    0.0
   0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0    0.0
   0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0    0.0
   0.0   0.0   0.0   0.0   0.0   0.0  …   0.0   0.0   0.0   0.0   0.0    0.0
   0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0    0.0
   0.0   0.0   0.0   0.0   0.0   0.0      0.0   

In [3]:
A=rand(250,250)

250×250 Array{Float64,2}:
 0.283305   0.399876  0.996531    …  0.821889    0.228658   0.437253 
 0.0111639  0.934202  0.655864       0.590829    0.998336   0.0371104
 0.378843   0.689979  0.648509       0.0255468   0.214491   0.809715 
 0.700758   0.287318  0.672918       0.393016    0.0576128  0.420028 
 0.253179   0.948127  0.159483       0.244923    0.644041   0.770206 
 0.878603   0.243369  0.550385    …  0.880158    0.0124362  0.600598 
 0.853577   0.935616  0.983381       0.52386     0.357323   0.500657 
 0.201465   0.391933  0.984205       0.866456    0.773029   0.262924 
 0.849907   0.419426  0.511998       0.0135614   0.423484   0.231634 
 0.41481    0.861074  0.799616       0.630088    0.580746   0.679093 
 0.588289   0.14112   0.675839    …  0.00132585  0.870484   0.221124 
 0.541151   0.421059  0.0892561      0.972141    0.766407   0.735369 
 0.0036349  0.479878  0.74687        0.179775    0.440264   0.520991 
 ⋮                                ⋱                             

In [7]:
#eigs(mat1; nev=1, which=:SR, maxiter=30000, ritzvec=true)
a=eigen(A).values

250-element Array{Complex{Float64},1}:
  125.41396548095642 + 0.0im                
 -2.9425950417837603 + 3.749086991767482im  
 -2.9425950417837603 - 3.749086991767482im  
   4.674208674673974 + 0.07751960731708274im
   4.674208674673974 - 0.07751960731708274im
  0.5449003174155647 + 4.535847271980686im  
  0.5449003174155647 - 4.535847271980686im  
  0.6367072821080706 + 4.511001883106541im  
  0.6367072821080706 - 4.511001883106541im  
   4.304581363138167 + 1.5076595175855005im 
   4.304581363138167 - 1.5076595175855005im 
   3.259364780147669 + 3.0903241754652737im 
   3.259364780147669 - 3.0903241754652737im 
                     ⋮                      
 -1.1278576858923317 + 0.0im                
  0.7987902453688017 + 0.45170459113781536im
  0.7987902453688017 - 0.45170459113781536im
 -0.0773063153620705 + 0.6903302631943014im 
 -0.0773063153620705 - 0.6903302631943014im 
  0.5367135364241407 + 0.5394369556128638im 
  0.5367135364241407 - 0.5394369556128638im 
 -0.734478838164

In [10]:
minimum(real(a))

-4.415835450377819

In [5]:
eigs(A; nev=1, which=:SR, maxiter=30000, ritzvec=true)

(Complex{Float64}[-4.41584+0.386514im], Complex{Float64}[-0.0537816+0.0578238im; -0.0372871-0.0225595im; … ; 0.0141866+0.0158362im; -0.00172167-0.0132415im], 2, 33, 565, [-0.189854, 0.029925, -0.0599931, -0.143891, -0.211121, -0.268856, 0.063188, -0.111288, -0.123887, -0.0258724  …  0.0709034, -0.0839707, -0.0098447, -0.408883, -0.457179, -0.0136734, 0.118291, -0.0127222, 0.133279, 0.0350222])

## (Ising) model, eigensystem

In [ ]:
eigens=eigs(mat2)

In [ ]:
mat2=Matrix(mat2)
gndst=eigvecs(mat2)[:,1]


data = Array{Float32}(undef, N+1)
for i in 0:N
    data[i+1] = EntEntr(gndst,collect(1:i))
end
plot(data)