# Hamilton matrices for spin models

Quantum states are represented by binary number which can be converted to a decimal number.

We start with state n, and by applying the algorithm provided in the lecture this state is modified by the operator $J_{i,j}^{\alpha}S_i^{\alpha}S_j^{\alpha}$.

We now want to construct a matrix using this algorithm.

In [36]:
using LinearAlgebra, SparseArrays, DelimitedFiles
#Specifying the number of particles and the interaction matrices 
N=3
jmat = zeros(Int8, N, N, 3);

In [ ]:
function MakeHam(jmat)
    ham = spzeros(Float64,2^N, 2^N) #create empty sparse
    for n in 0:2^N-1 #going trhough all possible states n
        nbin=digits(n, base = 2, pad = N) #finding the binary corresponding to n (the state)
        for i in 1:N #i,j going through the elements of the J-matrices
            for j in i+1:N
                zi=nbin[i] #the ith number of the binary number (0 or 1) 
                zj=nbin[j]
                l = n +(1-2zi)*2^(i-1)+(1-2zj)*2^(j-1)
                if jmat[i,j,1]>0
                    ham[l+1,n+1] += -(1/4)*jmat[i,j,1] #x-link
                end
                if jmat[i,j,2]>0
                    ham[l+1,n+1] += (1/4)*jmat[i,j,2]*(2zi-1)*(2zj-1) #y-link
                end
                if jmat[i,j,3]>0
                    ham[n+1,n+1] += -jmat[i,j,3]*(2zi-1)*(2zj-1) #z-link
                end
            end
        end
    end
    return ham
end

Now define J matrices and find the corresponding hamiltonian.

In [40]:
jmat = zeros(Int8, N, N, 3);

#Ising model
#jmat[1,2,3]=jmat[1,3,3]=jmat[2,3,3]=jmat[2,1,3]=jmat[3,1,3]=jmat[3,2,3]=-1
#jmat[1,2,3]=jmat[2,3,3]=jmat[2,1,3]=jmat[3,2,3]=-1
for i in 1:N-1
    jmat[i,i+1,3]=jmat[i+1,i,3]=1
end
mat1=Matrix(MakeHam(jmat))
mat1


N=14

#Heisenberg
jmat = zeros(Int8, N, N, 3);
for i in 1:N-1
    for a in 1:3
        jmat[i,i+1,a]=jmat[i+1,i,a]=-1
    end
end

mat2=Matrix(MakeHam(jmat));

#=
#Specified model
jmat = zeros(Int8, N, N, 3)
jmat[1,2,1]=jmat[2,3,2]=jmat[1,3,3]=1
mat3=Matrix(MakeHam(jmat))
display(mat3)=#

## Ising model, eigensystem

In [23]:
display(eigvals(mat1))
eigvecs(mat1)

8-element Array{Float64,1}:
 -2.0
 -2.0
  0.0
  0.0
  0.0
  0.0
  2.0
  2.0

8×8 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

## Heisenberg

In [ ]:
display(eigvals(mat2))
heiseigvec=eigvecs(mat2)

16384-element Array{Float64,1}:
 -13.92537712714985 
 -13.916273838919098
 -12.717687471967883
 -12.717687471967828
 -12.63396102124985 
 -12.624984411184782
 -12.41229434785721 
 -12.412294347857122
 -12.214670701987998
 -12.205716154945216
 -12.03523956481943 
 -12.0352395648193  
 -11.782072741078187
   ⋮                
  11.063524590163897
  11.063524590164102
  11.064516129032153
  11.064516129032203
  11.06451612903226 
  11.064516129032333
  11.124999973806547
  11.124999973806647
  11.125000026193444
  11.125000026193543
  13.0              
  13.0              

In [38]:
writedlm("heisgs.txt",heiseigvec[:,1])

## Specified model

In [13]:
display(eigvals(mat3))
eigvecs(mat3)

8-element Array{Float64,1}:
 -0.4330127018922194 
 -0.4330127018922194 
 -0.43301270189221935
 -0.43301270189221924
  0.43301270189221913
  0.43301270189221924
  0.4330127018922193 
  0.4330127018922194 

8×8 Array{Float64,2}:
 -0.627963      0.157402     -0.607916     …   0.137013      0.0     
 -1.11022e-16  -0.314681     -0.0814772       -0.569453     -0.627963
  0.0          -0.859723     -0.2226           0.416869      0.0     
  0.0           0.115226     -0.445026        -0.374328      0.0     
  5.55112e-17  -0.314681     -0.0814772       -0.569453      0.627963
  0.627963      0.157402     -0.607916     …   0.137013      0.0     
  0.459701      2.77556e-17  -7.63278e-17      5.55112e-17   0.0     
  0.0           0.0           0.0              0.0          -0.459701