# Hamilton matrices for spin models

Quantum states are represented by binary number which can be converted to a decimal number.

We start with state n, and by applying the algorithm provided in the lecture this state is modified by the operator $J_{i,j}^{\alpha}S_i^{\alpha}S_j^{\alpha}$.

We now want to construct a matrix using this algorithm.

In [1]:
using LinearAlgebra, SparseArrays, DelimitedFiles
#Specifying the number of particles and the interaction matrices 
N=3
jmat = zeros(Int8, N, N, 3);

In [2]:
function MakeHam(jmat)
    ham = spzeros(Float64,2^N, 2^N) #create empty sparse
    for n in 0:2^N-1 #going trhough all possible states n
        nbin=digits(n, base = 2, pad = N) #finding the binary corresponding to n (the state)
        for i in 1:N #i,j going through the elements of the J-matrices
            for j in i+1:N
                zi=nbin[i] #the ith number of the binary number (0 or 1) 
                zj=nbin[j]
                l = n +(1-2zi)*2^(i-1)+(1-2zj)*2^(j-1)
                ham[l+1,n+1] += -(1/4)*jmat[i,j,1] #x-link
                ham[l+1,n+1] += (1/4)*jmat[i,j,2]*(2zi-1)*(2zj-1) #y-link
                ham[n+1,n+1] += -jmat[i,j,3]*(2zi-1)*(2zj-1) #z-link
            end
        end
    end
    return ham
end

MakeHam (generic function with 1 method)

Now define J matrices and find the corresponding hamiltonian.

In [5]:
jmat = zeros(Int8, N, N, 3);

#Ising model
#jmat[1,2,3]=jmat[1,3,3]=jmat[2,3,3]=jmat[2,1,3]=jmat[3,1,3]=jmat[3,2,3]=-1
#jmat[1,2,3]=jmat[2,3,3]=jmat[2,1,3]=jmat[3,2,3]=-1
for i in 1:N-1
    jmat[i,i+1,3]=jmat[i+1,i,3]=1
end
mat1=Matrix(MakeHam(jmat))
mat1


N=8

#Heisenberg
jmat = zeros(Int8, N, N, 3);
for i in 1:N-1
    for a in 1:3
        jmat[i,i+1,a]=jmat[i+1,i,a]=-1
    end
end

mat2=Matrix(MakeHam(jmat));

#=
#Specified model
jmat = zeros(Int8, N, N, 3)
jmat[1,2,1]=jmat[2,3,2]=jmat[1,3,3]=1
mat3=Matrix(MakeHam(jmat))
display(mat3)=#

## Ising model, eigensystem

In [6]:
display(eigvals(mat1))
eigvecs(mat1)

256-element Array{Float64,1}:
 -7.0
 -7.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
 -5.0
  ⋮  
  5.0
  5.0
  5.0
  5.0
  5.0
  5.0
  5.0
  5.0
  5.0
  5.0
  7.0
  7.0

256×256 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.

## Heisenberg

In [7]:
display(eigvals(mat2))
heiseigvec=eigvecs(mat2)

256-element Array{Float64,1}:
 -7.591062169619456 
 -7.506559856938644 
 -6.191171730393382 
 -6.191171730393372 
 -5.938322978443187 
 -5.855226703328099 
 -5.607576502263833 
 -5.607576502263828 
 -5.211204694691963 
 -5.128319370989215 
 -5.0377689033176125
 -5.037768903317607 
 -4.716098629506644 
  ⋮                 
  5.063524594423383 
  5.06352459442339  
  5.064516124692643 
  5.064516124692674 
  5.064516133547394 
  5.0645161335474205
  5.124892669458118 
  5.124892669458127 
  5.125107246231683 
  5.125107246231692 
  7.0               
  7.0               

256×256 Array{Float64,2}:
  0.0           0.0          …   0.0          0.0          1.0  0.0
  8.94267e-76   0.0             -0.684541     0.0          0.0  0.0
 -2.25196e-74   0.0             -0.171282     0.0          0.0  0.0
  1.27246e-42   0.0              1.94724e-16  0.0          0.0  0.0
  4.76118e-73   0.0             -0.0434446    0.0          0.0  0.0
 -3.20433e-41   0.0          …   4.39374e-17  0.0          0.0  0.0
  1.64631e-40   0.0              1.4237e-17   0.0          0.0  0.0
  2.15031e-29   2.84927e-24     -3.48927e-16  0.0          0.0  0.0
 -1.00627e-71   0.0             -0.0133667    0.0          0.0  0.0
  3.84668e-40   0.0              8.77867e-18  0.0          0.0  0.0
 -3.4552e-39    9.2666e-38   …   1.9735e-17   0.0          0.0  0.0
 -5.12995e-28  -2.14857e-23     -4.75849e-17  0.0          0.0  0.0
  1.01106e-38   4.47173e-37      1.95241e-16  0.0          0.0  0.0
  ⋮                          ⋱                                  ⋮  
 -7.26024e-17  -1.0010

In [8]:
writedlm("heisgs.txt",heiseigvec[:,1])

## Specified model

In [13]:
display(eigvals(mat3))
eigvecs(mat3)

8-element Array{Float64,1}:
 -0.4330127018922194 
 -0.4330127018922194 
 -0.43301270189221935
 -0.43301270189221924
  0.43301270189221913
  0.43301270189221924
  0.4330127018922193 
  0.4330127018922194 

8×8 Array{Float64,2}:
 -0.627963      0.157402     -0.607916     …   0.137013      0.0     
 -1.11022e-16  -0.314681     -0.0814772       -0.569453     -0.627963
  0.0          -0.859723     -0.2226           0.416869      0.0     
  0.0           0.115226     -0.445026        -0.374328      0.0     
  5.55112e-17  -0.314681     -0.0814772       -0.569453      0.627963
  0.627963      0.157402     -0.607916     …   0.137013      0.0     
  0.459701      2.77556e-17  -7.63278e-17      5.55112e-17   0.0     
  0.0           0.0           0.0              0.0          -0.459701